<?php

namespace ForumBundle\Repository;

/**
 * ReponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReponseRepository extends \Doctrine\ORM\EntityRepository
{

    public function rechercheAction($id)
    {

        $query=$this->getEntityManager()
            ->createQuery("SELECT r from ForumBundle:Reponse r where r.id=:idd")
            ->setParameter('idd',$id);
        return $query->getResult();
    }

}
