forum:
    resource: "@ForumBundle/Controller/"
    type:     annotation
    prefix:   /

backoffice:
    resource: "@backofficeBundle/Resources/config/routing.yml"
    prefix:   /admin

shop:
    resource: "@shopBundle/Resources/config/routing.yml"
    prefix:   /shop

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

app:
    resource: '@AppBundle/Controller/'
    type: annotation

homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }


cart:
    path:     /cart
    defaults: { _controller: AppBundle:Default:cart }
commande:
    path:     /commande
    defaults: { _controller: AppBundle:Default:commande }
equipement:
    path:     /equipement
    defaults: { _controller: AppBundle:Default:equipement }
event:
    path:     /event
    defaults: { _controller: AppBundle:Default:event }
eventb:
    path:     /eventb
    defaults: { _controller: AppBundle:Default:eventb }
publicite:
    path:     /publicite
    defaults: { _controller: AppBundle:Default:publicite }
publiciteb:
    path:     /publiciteb
    defaults: { _controller: AppBundle:Default:publiciteb }
reclamation:
    path:     /reclamation
    defaults: { _controller: AppBundle:Default:reclamation }
shopb:
    path:     /shopb
    defaults: { _controller: AppBundle:Default:shopb }
reclamationb:
    path:     /reclamationb
    defaults: { _controller: AppBundle:Default:reclamationb }
fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix: /chatroom