<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'AppBundle\EventListner\RedirectAfterRegistrationSubscriber' shared autowired service.

include_once $this->targetDirs[3].'\\src\\AppBundle\\EventListner\\RedirectAfterRegistrationSubscriber.php';

return $this->services['AppBundle\EventListner\RedirectAfterRegistrationSubscriber'] = new \AppBundle\EventListner\RedirectAfterRegistrationSubscriber(${($_ = isset($this->services['router']) ? $this->services['router'] : $this->getRouterService()) && false ?: '_'});
