<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2dmvj5t\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2dmvj5t/appProdProjectContainer.php') {
    touch(__DIR__.'/Container2dmvj5t.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container2dmvj5t\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container2dmvj5t\appProdProjectContainer([
    'container.build_hash' => '2dmvj5t',
    'container.build_id' => '95edab3c',
    'container.build_time' => 1550063696,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2dmvj5t');
