<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUxsk8jf\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUxsk8jf/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerUxsk8jf.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerUxsk8jf\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerUxsk8jf\appDevDebugProjectContainer([
    'container.build_hash' => 'Uxsk8jf',
    'container.build_id' => '59b0e6ab',
    'container.build_time' => 1556128402,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUxsk8jf');
